name: ChatShop
main: eddir\ChatShop
version: 1.2
api: [1.0.0]
author: eddir
website: vk.com/eddir
commands:
 shop:
  description: [ChatShop] Help command
  usage: /shop
 price:
  description: [ChatShop] Price command
  usage: /price [id]
 buy:
  description: [ChatShop] Buy command
  usage: /buy [id] [amount]
 sell:
  description: [ChatShop] Sell command
  usage: /sell [id] [amount]
